<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class MedicineSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        // Retrieve category IDs from the categories table
        $categories = DB::table('categories')->pluck('id', 'name')->toArray();

        $medicines = [
            [
                'slug' => Str::slug('Amoxicillin 500mg'),
                'name' => 'Amoxicillin 500mg',
                'category_id' => $categories['Antibiotics'],
                'batch_number' => 'AMOX2025-001',
                'expiry_date' => '2026-12-31',
                'cost_price' => 0.20,
                'selling_price' => 0.50,
                'stock_quantity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => Str::slug('Azithromycin 250mg'),
                'name' => 'Azithromycin 250mg',
                'category_id' => $categories['Antibiotics'],
                'batch_number' => 'AZI2025-002',
                'expiry_date' => '2027-06-30',
                'cost_price' => 0.40,
                'selling_price' => 1.00,
                'stock_quantity' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => Str::slug('Cefixime 200mg'),
                'name' => 'Cefixime 200mg',
                'category_id' => $categories['Antibiotics'],
                'batch_number' => 'CEF2025-003',
                'expiry_date' => '2026-09-30',
                'cost_price' => 0.50,
                'selling_price' => 1.20,
                'stock_quantity' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => Str::slug('Ibuprofen 400mg'),
                'name' => 'Ibuprofen 400mg',
                'category_id' => $categories['Painkillers'],
                'batch_number' => 'IBU2025-004',
                'expiry_date' => '2027-03-31',
                'cost_price' => 0.15,
                'selling_price' => 0.40,
                'stock_quantity' => 200,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => Str::slug('Paracetamol 500mg'),
                'name' => 'Paracetamol 500mg',
                'category_id' => $categories['Painkillers'],
                'batch_number' => 'PAR2025-005',
                'expiry_date' => '2028-01-31',
                'cost_price' => 0.05,
                'selling_price' => 0.15,
                'stock_quantity' => 500,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => Str::slug('Diclofenac 50mg'),
                'name' => 'Diclofenac 50mg',
                'category_id' => $categories['Painkillers'],
                'batch_number' => 'DIC2025-006',
                'expiry_date' => '2026-11-30',
                'cost_price' => 0.25,
                'selling_price' => 0.60,
                'stock_quantity' => 150,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => Str::slug('Omeprazole 20mg'),
                'name' => 'Omeprazole 20mg',
                'category_id' => $categories['Antacids'],
                'batch_number' => 'OME2025-007',
                'expiry_date' => '2027-04-30',
                'cost_price' => 0.30,
                'selling_price' => 0.75,
                'stock_quantity' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => Str::slug('Ranitidine 150mg'),
                'name' => 'Ranitidine 150mg',
                'category_id' => $categories['Antacids'],
                'batch_number' => 'RAN2025-008',
                'expiry_date' => '2026-10-31',
                'cost_price' => 0.20,
                'selling_price' => 0.50,
                'stock_quantity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => Str::slug('Pantoprazole 40mg'),
                'name' => 'Pantoprazole 40mg',
                'category_id' => $categories['Antacids'],
                'batch_number' => 'PAN2025-009',
                'expiry_date' => '2027-02-28',
                'cost_price' => 10,
                'selling_price' => 15,
                'stock_quantity' => 90,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => Str::slug('Loratadine 10mg'),
                'name' => 'Loratadine 10mg',
                'category_id' => $categories['Antihistamines'],
                'batch_number' => 'LOR2025-010',
                'expiry_date' => '2027-05-31',
                'cost_price' => 100,
                'selling_price' => 140,
                'stock_quantity' => 200,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => Str::slug('Cetirizine 10mg'),
                'name' => 'Cetirizine 10mg',
                'category_id' => $categories['Antihistamines'],
                'batch_number' => 'CET2025-011',
                'expiry_date' => '2026-08-31',
                'cost_price' => 0.08,
                'selling_price' => 0.25,
                'stock_quantity' => 250,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => Str::slug('Fexofenadine 180mg'),
                'name' => 'Fexofenadine 180mg',
                'category_id' => $categories['Antihistamines'],
                'batch_number' => 'FEX2025-012',
                'expiry_date' => '2027-07-31',
                'cost_price' => 0.30,
                'selling_price' => 0.70,
                'stock_quantity' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => Str::slug('Amlodipine 5mg'),
                'name' => 'Amlodipine 5mg',
                'category_id' => $categories['Cardiovascular'],
                'batch_number' => 'AML2025-013',
                'expiry_date' => '2026-12-31',
                'cost_price' => 0.15,
                'selling_price' => 0.40,
                'stock_quantity' => 150,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => Str::slug('Atenolol 50mg'),
                'name' => 'Atenolol 50mg',
                'category_id' => $categories['Cardiovascular'],
                'batch_number' => 'ATE2025-014',
                'expiry_date' => '2027-03-31',
                'cost_price' => 0.20,
                'selling_price' => 0.50,
                'stock_quantity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => Str::slug('Losartan 50mg'),
                'name' => 'Losartan 50mg',
                'category_id' => $categories['Cardiovascular'],
                'batch_number' => 'LOS2025-015',
                'expiry_date' => '2026-11-30',
                'cost_price' => 0.25,
                'selling_price' => 0.60,
                'stock_quantity' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => Str::slug('Metformin 500mg'),
                'name' => 'Metformin 500mg',
                'category_id' => $categories['Antidiabetics'],
                'batch_number' => 'MET2025-016',
                'expiry_date' => '2027-01-31',
                'cost_price' => 0.10,
                'selling_price' => 0.30,
                'stock_quantity' => 200,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => Str::slug('Gliclazide 80mg'),
                'name' => 'Gliclazide 80mg',
                'category_id' => $categories['Antidiabetics'],
                'batch_number' => 'GLI2025-017',
                'expiry_date' => '2026-10-31',
                'cost_price' => 0.20,
                'selling_price' => 0.50,
                'stock_quantity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => Str::slug('Sitagliptin 100mg'),
                'name' => 'Sitagliptin 100mg',
                'category_id' => $categories['Antidiabetics'],
                'batch_number' => 'SIT2025-018',
                'expiry_date' => '2027-06-30',
                'cost_price' => 0.50,
                'selling_price' => 1.20,
                'stock_quantity' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => Str::slug('Vitamin D3 1000IU'),
                'name' => 'Vitamin D3 1000IU',
                'category_id' => $categories['Vitamins'],
                'batch_number' => 'VITD2025-019',
                'expiry_date' => '2028-02-28',
                'cost_price' => 0.05,
                'selling_price' => 0.15,
                'stock_quantity' => 300,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => Str::slug('Vitamin C 500mg'),
                'name' => 'Vitamin C 500mg',
                'category_id' => $categories['Vitamins'],
                'batch_number' => 'VITC2025-020',
                'expiry_date' => '2027-09-30',
                'cost_price' => 0.07,
                'selling_price' => 0.20,
                'stock_quantity' => 250,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => Str::slug('Multivitamin Tablets'),
                'name' => 'Multivitamin Tablets',
                'category_id' => $categories['Vitamins'],
                'batch_number' => 'MULTI2025-021',
                'expiry_date' => '2027-12-31',
                'cost_price' => 0.10,
                'selling_price' => 0.30,
                'stock_quantity' => 200,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => Str::slug('Acyclovir 400mg'),
                'name' => 'Acyclovir 400mg',
                'category_id' => $categories['Antivirals'],
                'batch_number' => 'ACY2025-022',
                'expiry_date' => '2026-10-31',
                'cost_price' => 0.35,
                'selling_price' => 0.80,
                'stock_quantity' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => Str::slug('Oseltamivir 75mg'),
                'name' => 'Oseltamivir 75mg',
                'category_id' => $categories['Antivirals'],
                'batch_number' => 'OSE2025-023',
                'expiry_date' => '2027-05-31',
                'cost_price' => 0.60,
                'selling_price' => 1.50,
                'stock_quantity' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => Str::slug('Valacyclovir 500mg'),
                'name' => 'Valacyclovir 500mg',
                'category_id' => $categories['Antivirals'],
                'batch_number' => 'VAL2025-024',
                'expiry_date' => '2026-12-31',
                'cost_price' => 0.45,
                'selling_price' => 1.10,
                'stock_quantity' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => Str::slug('Clotrimazole Cream 1%'),
                'name' => 'Clotrimazole Cream 1%',
                'category_id' => $categories['Antifungals'],
                'batch_number' => 'CLO2025-025',
                'expiry_date' => '2027-04-30',
                'cost_price' => 2.00,
                'selling_price' => 5.00,
                'stock_quantity' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => Str::slug('Fluconazole 150mg'),
                'name' => 'Fluconazole 150mg',
                'category_id' => $categories['Antifungals'],
                'batch_number' => 'FLU2025-026',
                'expiry_date' => '2026-11-30',
                'cost_price' => 0.50,
                'selling_price' => 1.20,
                'stock_quantity' => 70,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => Str::slug('Ketoconazole Cream 2%'),
                'name' => 'Ketoconazole Cream 2%',
                'category_id' => $categories['Antifungals'],
                'batch_number' => 'KET2025-027',
                'expiry_date' => '2027-03-31',
                'cost_price' => 2.50,
                'selling_price' => 6.00,
                'stock_quantity' => 40,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => Str::slug('Hydrocortisone Cream 1%'),
                'name' => 'Hydrocortisone Cream 1%',
                'category_id' => $categories['Topical'],
                'batch_number' => 'HYD2025-028',
                'expiry_date' => '2026-08-31',
                'cost_price' => 1.50,
                'selling_price' => 4.00,
                'stock_quantity' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => Str::slug('Betamethasone Cream 0.1%'),
                'name' => 'Betamethasone Cream 0.1%',
                'category_id' => $categories['Topical'],
                'batch_number' => 'BET2025-029',
                'expiry_date' => '2027-02-28',
                'cost_price' => 2.00,
                'selling_price' => 5.00,
                'stock_quantity' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => Str::slug('Lidocaine Gel 2%'),
                'name' => 'Lidocaine Gel 2%',
                'category_id' => $categories['Topical'],
                'batch_number' => 'LID2025-030',
                'expiry_date' => '2026-09-30',
                'cost_price' => 3.00,
                'selling_price' => 7.50,
                'stock_quantity' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('medicines')->insert($medicines);
    }
}
